export default {
  login: "Spittzzer",
  id: 59199755,
  node_id: "MDQ6VXNlcjU5MTk5NzU1",
  avatar_url: "https://avatars.githubusercontent.com/u/59199755?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Spittzzer",
  html_url: "https://github.com/Spittzzer",
  followers_url: "https://api.github.com/users/Spittzzer/followers",
  following_url:
    "https://api.github.com/users/Spittzzer/following{/other_user}",
  gists_url: "https://api.github.com/users/Spittzzer/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Spittzzer/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Spittzzer/subscriptions",
  organizations_url: "https://api.github.com/users/Spittzzer/orgs",
  repos_url: "https://api.github.com/users/Spittzzer/repos",
  events_url: "https://api.github.com/users/Spittzzer/events{/privacy}",
  received_events_url: "https://api.github.com/users/Spittzzer/received_events",
  type: "User",
  site_admin: false,
  name: "Bilel Aoun",
  company: null,
  blog: "",
  location: "France",
  email: null,
  hireable: null,
  bio: "A self taught web developer from France striving to learn new things, improve and get better at my craft .",
  twitter_username: null,
  public_repos: 39,
  public_gists: 0,
  followers: 7,
  following: 13,
  created_at: "2019-12-24T11:27:15Z",
  updated_at: "2022-06-04T15:06:43Z",
};
